-- MySQL Script generated by MySQL Workbench
-- Fri Sep 16 00:09:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OS` (
  `idOS` INT NOT NULL AUTO_INCREMENT,
  `DataInicio` DATE NOT NULL,
  `ValTotal` INT NOT NULL,
  `Autorizado` TINYINT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `DataFim` DATE NULL,
  PRIMARY KEY (`idOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` INT NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Nascimento` DATE NULL,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Pessoa_idPessoa` INT NOT NULL,
  `Codigo` INT NOT NULL,
  `Credito` INT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Pessoa_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Pessoa`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Chassi` VARCHAR(45) NOT NULL,
  `Placa` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `Cliente_idCliente`),
  UNIQUE INDEX `Placa_UNIQUE` (`Placa` ASC) VISIBLE,
  INDEX `fk_Veiculo_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Setor` (
  `idSetor` INT NOT NULL AUTO_INCREMENT,
  `Funcao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSetor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `Setor_idSetor` INT NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  `Codigo` INT NOT NULL,
  `Especialdiade` VARCHAR(45) NOT NULL,
  `Salario` INT NULL,
  PRIMARY KEY (`idFuncionario`, `Setor_idSetor`),
  INDEX `fk_Funcionario_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Funcionario_Setor1_idx` (`Setor_idSetor` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Setor1`
    FOREIGN KEY (`Setor_idSetor`)
    REFERENCES `mydb`.`Setor` (`idSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AberturaOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AberturaOS` (
  `OS_idOS` INT NOT NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  `Veiculo_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`OS_idOS`, `Veiculo_idVeiculo`, `Veiculo_Cliente_idCliente`),
  INDEX `fk_OS_has_Cliente_OS1_idx` (`OS_idOS` ASC) VISIBLE,
  INDEX `fk_AberturaOS_Veiculo1_idx` (`Veiculo_idVeiculo` ASC, `Veiculo_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_OS_has_Cliente_OS1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `mydb`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AberturaOS_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo` , `Veiculo_Cliente_idCliente`)
    REFERENCES `mydb`.`Veiculo` (`idVeiculo` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `ServicoRealizado` VARCHAR(45) NOT NULL,
  `Custo` INT NOT NULL,
  `ValorTotal` INT NOT NULL,
  `Setor_idSetor` INT NOT NULL,
  PRIMARY KEY (`idServico`, `Setor_idSetor`),
  INDEX `fk_Servico_Setor1_idx` (`Setor_idSetor` ASC) VISIBLE,
  CONSTRAINT `fk_Servico_Setor1`
    FOREIGN KEY (`Setor_idSetor`)
    REFERENCES `mydb`.`Setor` (`idSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ServicoRealizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ServicoRealizado` (
  `OS_idOS` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  PRIMARY KEY (`OS_idOS`, `Servico_idServico`),
  INDEX `fk_OS_has_Servico_Servico1_idx` (`Servico_idServico` ASC) VISIBLE,
  INDEX `fk_OS_has_Servico_OS1_idx` (`OS_idOS` ASC) VISIBLE,
  CONSTRAINT `fk_OS_has_Servico_OS1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `mydb`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_has_Servico_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pecas` (
  `idPecas` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Veiculo` VARCHAR(45) NULL,
  `Valor` INT NULL,
  PRIMARY KEY (`idPecas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PecasUtilizadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PecasUtilizadas` (
  `Pecas_idPecas` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  `Qnt` INT NOT NULL,
  `ValorTotal` INT NOT NULL,
  PRIMARY KEY (`Pecas_idPecas`, `Servico_idServico`),
  INDEX `fk_Pecas_has_Servico_Servico1_idx` (`Servico_idServico` ASC) VISIBLE,
  INDEX `fk_Pecas_has_Servico_Pecas1_idx` (`Pecas_idPecas` ASC) VISIBLE,
  CONSTRAINT `fk_Pecas_has_Servico_Pecas1`
    FOREIGN KEY (`Pecas_idPecas`)
    REFERENCES `mydb`.`Pecas` (`idPecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pecas_has_Servico_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
