-- MySQL Script generated by MySQL Workbench
-- Fri Sep 16 00:03:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NOT NULL,
  `CodBarras` INT NULL,
  `Descricao` VARCHAR(50) NOT NULL,
  `UnMedida` VARCHAR(3) NOT NULL,
  `PrecoForn` INT NOT NULL,
  `PrecoMin` INT NULL,
  `PrecoVend` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `CPF/CNPJ` VARCHAR(25) NOT NULL,
  `Endereco` VARCHAR(40) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `CPF/CNPJ_UNIQUE` (`CPF/CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transportadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transportadora` (
  `idDistribuidora` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Veiculo` VARCHAR(45) NOT NULL,
  `Placa` INT NOT NULL,
  `Motorista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDistribuidora`),
  UNIQUE INDEX `Placa_UNIQUE` (`Placa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `idDistribuicao` INT NOT NULL AUTO_INCREMENT,
  `Correio` TINYINT NOT NULL,
  `Transportadora` TINYINT NOT NULL,
  `CRastreio` INT NOT NULL,
  `Prazo` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Transportadora_idDistribuidora` INT NOT NULL,
  PRIMARY KEY (`idDistribuicao`, `Transportadora_idDistribuidora`),
  INDEX `fk_Distribuicao_Transportadora1_idx` (`Transportadora_idDistribuidora` ASC) VISIBLE,
  CONSTRAINT `fk_Distribuicao_Transportadora1`
    FOREIGN KEY (`Transportadora_idDistribuidora`)
    REFERENCES `mydb`.`Transportadora` (`idDistribuidora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT NOT NULL,
  `TotPedido` INT NOT NULL,
  `Pago` TINYINT NOT NULL,
  `DataPagamento` DATE NULL,
  `Entrega_idDistribuicao` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`, `Entrega_idDistribuicao`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Entrega1_idx` (`Entrega_idDistribuicao` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Entrega1`
    FOREIGN KEY (`Entrega_idDistribuicao`)
    REFERENCES `mydb`.`Entrega` (`idDistribuicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF/CNPJ` INT NOT NULL,
  `Endereco` VARCHAR(50) NOT NULL,
  `Vendedor` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `CPF/CNPJ_UNIQUE` (`CPF/CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `NNota` INT NOT NULL,
  `DataEntrada` DATE NULL,
  `NLote` INT NULL,
  `Validade` INT NULL,
  `QuantMIN` INT NULL,
  `QuantATUAL` INT NOT NULL,
  PRIMARY KEY (`idEstoque`, `Fornecedor_idFornecedor`, `Produto_idProduto`),
  INDEX `fk_Estoque_Fornecedor_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  INDEX `fk_Estoque_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Fornecedor`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartão`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cartão` (
  `idCartão` INT NOT NULL AUTO_INCREMENT,
  `Credito` TINYINT NOT NULL,
  `Debito` TINYINT NOT NULL,
  `NCartao` INT NOT NULL,
  `Valdiade` DATE NOT NULL,
  `Proprietario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCartão`),
  UNIQUE INDEX `NCartao_UNIQUE` (`NCartao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoPagamento` (
  `idFormaPagamento` INT NOT NULL AUTO_INCREMENT,
  `Cartão_idCartão` INT NOT NULL,
  `Dinheiro` TINYINT NOT NULL,
  `Cartao` TINYINT NOT NULL,
  PRIMARY KEY (`idFormaPagamento`, `Cartão_idCartão`),
  INDEX `fk_FormaPagamento_Cartão1_idx` (`Cartão_idCartão` ASC) VISIBLE,
  CONSTRAINT `fk_FormaPagamento_Cartão1`
    FOREIGN KEY (`Cartão_idCartão`)
    REFERENCES `mydb`.`Cartão` (`idCartão`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FormaPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FormaPagamento` (
  `Pedido_idPedido` INT NOT NULL,
  `FormaPagamento_idFormaPagamento` INT NOT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `FormaPagamento_idFormaPagamento`),
  INDEX `fk_Pedido_has_FormaPagamento_FormaPagamento1_idx` (`FormaPagamento_idFormaPagamento` ASC) VISIBLE,
  INDEX `fk_Pedido_has_FormaPagamento_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_FormaPagamento_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_FormaPagamento_FormaPagamento1`
    FOREIGN KEY (`FormaPagamento_idFormaPagamento`)
    REFERENCES `mydb`.`TipoPagamento` (`idFormaPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido_has_Produto` (
  `Pedido_idPedido` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Produto_idProduto`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Produto_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
